FROM pistensau/dbmonlab:latest

ARG APPD_AGENT_VERSION
ARG CONTROLLER_HOST
ARG CONTROLLER_PORT
ARG ACCOUNT_NAME
ARG ACCOUNT_ACCESS_KEY
ARG APPD_AGENT_VERSION

ENV APPD_AGENT_VERSION ${APPD_AGENT_VERSION:-4.2.6.1}
ENV CONTROLLER_HOST=${CONTROLLER_HOST}
ENV CONTROLLER_PORT=${CONTROLLER_PORT}
ENV ACCOUNT_NAME "${ACCOUNT_NAME}"
ENV ACCOUNT_ACCESS_KEY="${ACCOUNT_ACCESS_KEY}"

EXPOSE 1521
